

server:
  port: 8888

spring:
  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:3306/test_quartz?characterEncoding=utf8&useSSL=false&autoReconnect=true&serverTimezone=UTC
      username: tom
      password: tom
      driver-class-name: com.mysql.jdbc.Driver
      db-type: com.alibaba.druid.pool.DruidDataSource
      initial-size: 3
      min-idle: 3
      max-active: 10
      max-wait: 60000

mybatis:
  mapper-locations: classpath:org/example/mapper/*.xml
  configuration:
    cache-enabled: true
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



















